### ISSUE TITLE
create-multipage-web-application-by-using-create-react-app

### ISSUE THREAD

**Issue by myuanyuan** [y2x33/y2x33.github.io#2]
关于create-multipage-web-application-by-using-create-react-app这篇文章有点问题想请教一下，build和start都没报错，可惜的是代码并没有打包进去，start也是空白页面，demo地址https://github.com/myuanyuan/multipage-web-application      
多谢

**Comment by y2x33** [comment]
HtmlWebpackPlugin 处，filename 改用字符串模板即可（记得dev和 prod都要修改）。
```javascript
// from
filename: app + '.html'

//to
filename: `${app}.html`
```
